export const newAnimationsList = [
  {id: 1, title:"ひだまりスケッチ", season:"2007冬", category: "日常", part: "12", recorder: "sota"},
]
export const animationsList = [
  // urlは全部ひだまりスケッチ
  // 2007
  {title:"ひだまりスケッチ", season:"2007冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"天元突破グレンラガン", season:"2007春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"エヴァンゲリオン新劇場版：序", season:"2007夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"みなみけ", season:"2007秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2008
  {title:"夏目友人帳", season:"2008夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"とらドラ！", season:"2008冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"とある魔術の禁書目録", season:"2008冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2009
  {title:"みなみけ おかえり", season:"2009冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"涼宮ハルヒちゃんの憂鬱", season:"2009冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"けいおん！", season:"2009春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"涼宮ハルヒの憂鬱", season:"2009春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"エヴァンゲリオン新劇場版：破", season:"2009春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"東のエデン", season:"2009春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"化物語", season:"2009夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"とある科学の超電磁砲", season:"2009秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2010
  {title:"涼宮ハルヒの消失", season:"2010冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"バカとテストと召喚獣", season:"2010冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"けいおん！！", season:"2010春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"Angel Beats!", season:"2010春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"四畳半神話大系", season:"2010春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"東のエデン 劇場版Ⅱ Paradise Lost", season:"2010春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"生徒会役員共", season:"2010夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2011
  {title:"魔法少女まどか☆マギカ", season:"2011冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"日常", season:"2011春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"Fate/Zero 1stシーズン", season:"2011秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"映画 けいおん！", season:"2011秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2012
  {title:"偽物語", season:"2012冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"猫物語(黒)", season:"2012冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"男子高校生の日常", season:"2012冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"妖狐×僕SS", season:"2012冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"氷菓", season:"2012春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"Fate/Zero 2ndシーズン", season:"2012春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ソードアートオンライン", season:"2012夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"中二病でも恋がしたい！ Lite", season:"2012夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"PSYCHO-PASS サイコパス", season:"2012秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"中二病でも恋がしたい！", season:"2012秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ヱヴァンゲリヲン 新劇場版：Q", season:"2012秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2013
  {title:"みなみけ　ただいま", season:"2013冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"やはり俺の青春ラブコメはまちがっている。", season:"2013春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"＜物語＞シリーズ セカンドシーズン", season:"2013夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"きんいろモザイク", season:"2013夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"劇場版 魔法少女まどか☆マギカ [新編] 叛逆の物語", season:"2013秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"キルラキル KILL la KILL", season:"2013秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"のんのんびより", season:"2013秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"境界の彼方", season:"2013秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2014
  {title:"中二病でも恋がしたい！戀", season:"2014冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"生徒会役員共＊", season:"2014冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ノーゲーム・ノーライフ", season:"2014春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ご注文はうさぎですか？", season:"2014春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"魔法科高校の劣等生", season:"2014春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ソードアート・オンラインII", season:"2014夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"SHIROBAKO", season:"2014秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"四月は君の嘘", season:"2014秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"甘城ブリリアントパーク", season:"2014秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2015
  {title:"冴えない彼女の育て方", season:"2015冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ダンジョンに出会いを求めるのは間違っているだろうか", season:"2015春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"やはり俺の青春ラブコメはまちがっている。続", season:"2015春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"長門有希ちゃんの消失", season:"2015春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"Charlotte", season:"2015夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"がっこうぐらし！", season:"2015夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"のんのんびより りぴーと", season:"2015夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"オーバーロード", season:"2015夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"下ネタという概念が存在しない退屈な世界", season:"2015夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ワンパンマン", season:"2015秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ご注文はうさぎですか？？", season:"2015秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2016
  {title:"この素晴らしい世界に祝福を！", season:"2016冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"Re:ゼロから始める異世界生活", season:"2016春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"甲鉄城のカバネリ", season:"2016春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"NEW GAME!", season:"2016夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"月曜日のたわわ", season:"2016秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"Occultic;Nine-オカルティック・ナイン-", season:"2016秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2017
  {title:"小林さんちのメイドラゴン", season:"2017冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"幼女戦記", season:"2017冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ガヴリールドロップアウト", season:"2017冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"エロマンガ先生", season:"2017春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"冴えない彼女の育てかた♭", season:"2017春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"劇場版 魔法科高校の劣等生 星を呼ぶ少女", season:"2017春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"NEW GAME!!", season:"2017夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"メイドインアビス", season:"2017夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"少女終末旅行", season:"2017秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ブレンド・S", season:"2017秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2018
  {title:"ゆるキャン△", season:"2018冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"宇宙よりも遠い場所", season:"2018冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ダーリン・イン・ザ・フランキス", season:"2018冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"オーバーロードⅡ", season:"2018冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"映画 中二病でも恋がしたい！ -Take On Me-", season:"2018冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ヒナまつり", season:"2018春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"宇宙戦艦ティラミス", season:"2018春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"あそびあそばせ", season:"2018夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"劇場版 のんのんびより ばけーしょん", season:"2018夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ソードアート・オンライン アリシゼーション", season:"2018秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"転生したらスライムだった件", season:"2018秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"SSSS.GRIDMAN", season:"2018秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"Re:ゼロから始める異世界生活 Memory Snow", season:"2018秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"寄宿学校のジュリエット", season:"2018秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"宇宙戦艦ティラミスII", season:"2018秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2019
  {title:"かぐや様は告らせたい〜天才たちの恋愛頭脳戦〜", season:"2019冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"約束のネバーランド", season:"2019冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"五等分の花嫁", season:"2019冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ケムリクサ", season:"2019冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"劇場版 幼女戦記", season:"2019冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"鬼滅の刃", season:"2019春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"異世界かるてっと", season:"2019春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"甲鉄城のカバネリ 〜海門決戦〜", season:"2019春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ダンジョンに出会いを求めるのは間違っているだろうか II", season:"2019夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"彼方のアストラ", season: "2019夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"魔法少女まどかまぎか", season: "2019夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"まちカドまぞく", season:"2019夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"可愛ければ変態でも好きになってくれますか？", season:"2019夏", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"慎重勇者 ～この勇者が俺TUEEEくせに慎重すぎる～", season:"2019秋", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  // 2020
  {title:"へやキャン△", season:"2020冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"マギアレコード 魔法少女まどか☆マギカ外伝", season:"2020冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"恋する小惑星", season:"2020冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"劇場版 SHIROBAKO", season:"2020冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"メイドインアビス 深き魂の黎明", season:"2020冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"異世界かるてっと2", season:"2020冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"Re:ゼロから始める異世界生活 新編集版", season:"2020冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"ソマリと森の神様", season:"2020冬", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"かぐや様は告らせたい？～天才たちの恋愛頭脳戦～", season:"2020春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
  {title:"乙女ゲームの破滅フラグしかない悪役令嬢に転生してしまった…", season:"2020春", url: "https://anime.dmkt-sp.jp/animestore/ci_pc?workId=21437"},
];